language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm: 2.1.5
sudo: false
services:
  - memcached
branches:
  only: [master]
env:
  matrix:
    - DB=sqlite BUNDLE_WITHOUT=mysql2:postgresql
    - DB=mysql BUNDLE_WITHOUT=sqlite:postgresql
    - DB=postgresql BUNDLE_WITHOUT=sqlite:mysql2

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - npm install
script:
  - npm run-script jshint
  - npm test
  - bundle exec rake test:js
  - bundle exec rake
