services:
  - memcached
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - npm install
env:
  matrix:
    - DB=sqlite BUNDLE_WITHOUT=mysql2:postgresql
    - DB=mysql BUNDLE_WITHOUT=sqlite:postgresql
    - DB=postgresql BUNDLE_WITHOUT=sqlite:mysql2
  global:
    - SECRET_TOKEN=d6054cf90db212c8fbc070c896c30398e3275532c5602bdf00cb153b806c000e4e46fac2f3acc0783822b8f6d30b5913b6fbcfdd24914553e745b8aa8ddfa5a4
    - DEFAULT_URL=http://www.test-url.com
    - ZENDESK_TOKEN=c30398e3275532c5602bdf00cb153b806c000e4e46fac2f3acc0783822b8f6d3
    - ZENDESK_URL=https://test.support.zendesk
script:
  - npm test
  - bundle exec rake
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  webhooks:
    - secure: "kTQxdTP7M+GpR/eaYbUJm+p/+TCAf+cQbeGDzw8C4qzThBDqn602i3seUUuTEmvY6tsNDqCrN7ggWEzQ/pbkhxun5oI4qoI1F//fQmMLYmGBJSiP3RdoGkiwuoqqo/iNxWcxGlub/E5AQhKR0fR2NrO+nv6a2QqKAo2qpWmfUFs="
rvm: 2.1.5
sudo: false
