language: ruby
cache:
  bundler: true
  directories:
    - node_modules
sudo: false
services:
  - memcached
branches:
  only: master
env:
  matrix:
    - DATABASE_URL=mysql2://none@none/none TASK='test:prepare_js test:js'
    - DATABASE_URL=mysql2://none@none/none TASK='assets:precompile'
    - TASK='brakeman'
    - BUNDLE_WITHOUT=postgres:sqlite DATABASE_URL=mysql2://travis@127.0.0.1/samson_test USE_UTF8MB4=1 TASK='db:create default'
    - BUNDLE_WITHOUT=mysql:sqlite DATABASE_URL=postgresql://postgres@127.0.0.1/samson_test TASK='db:create default'
    - BUNDLE_WITHOUT=postgres:mysql DATABASE_URL=sqlite3://null$PWD/db/test.sqlite3 TASK='db:create default'
script: bundle exec rake $TASK
before_script:
  - mysql -u root -e 'set GLOBAL innodb_large_prefix = true'
  - mysql -u root -e 'set GLOBAL innodb_file_per_table = true'
  - mysql -u root -e 'set GLOBAL innodb_file_format = "barracuda"'
